import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { CheckCircle, AlertTriangle, TrendingUp, Shield, DollarSign, Calendar, Lightbulb, ArrowRight } from "lucide-react"
import { cn } from "@/lib/utils"

interface InsightsPanelProps {
  insights: string[]
  recommendations: string[]
}

export function InsightsPanel({ insights, recommendations }: InsightsPanelProps) {

  const getInsightIcon = (insight: string) => {
    if (insight.toLowerCase().includes("save") || insight.toLowerCase().includes("lower")) {
      return <DollarSign className="w-4 h-4 text-[hsl(var(--success))]" />
    }
    if (insight.toLowerCase().includes("gap") || insight.toLowerCase().includes("missing")) {
      return <AlertTriangle className="w-4 h-4 text-[hsl(var(--warning))]" />
    }
    if (insight.toLowerCase().includes("expir") || insight.toLowerCase().includes("renew")) {
      return <Calendar className="w-4 h-4 text-muted-foreground" />
    }
    if (insight.toLowerCase().includes("coverage") || insight.toLowerCase().includes("protect")) {
      return <Shield className="w-4 h-4 text-foreground" />
    }
    return <TrendingUp className="w-4 h-4 text-primary" />
  }

  const getInsightType = (insight: string) => {
    if (insight.toLowerCase().includes("save") || insight.toLowerCase().includes("lower")) {
      return { type: "savings", variant: "outline" as const, className: "text-[hsl(var(--success))] border-[hsl(var(--success))/30] bg-[hsl(var(--success))/5]" }
    }
    if (insight.toLowerCase().includes("gap") || insight.toLowerCase().includes("missing")) {
      return { type: "warning", variant: "outline" as const, className: "text-[hsl(var(--warning))] border-[hsl(var(--warning))/30] bg-[hsl(var(--warning))/5]" }
    }
    if (insight.toLowerCase().includes("expir") || insight.toLowerCase().includes("renew")) {
      return { type: "renewal", variant: "outline" as const, className: "text-muted-foreground border-border bg-muted/30" }
    }
    return { type: "general", variant: "secondary" as const, className: "" }
  }

  return (
    <div className="space-y-6">
      <Alert className="bg-muted/50 border-muted-foreground/20">
        <Lightbulb className="h-4 w-4 text-[hsl(var(--warning))]" />
        <AlertTitle className="text-sm font-medium text-foreground">AI-Generated Insights</AlertTitle>
        <AlertDescription className="text-xs text-muted-foreground">
          These insights are generated by AI based on your policy documents. Please verify with your insurer.
        </AlertDescription>
      </Alert>

      <div className="flex items-center gap-6 p-4 rounded-lg border bg-card">
        <div className="flex items-center gap-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-muted">
            <TrendingUp className="h-4 w-4 text-foreground" />
          </div>
          <div>
            <p className="metric-label">Total Insights</p>
            <p className="text-xl font-semibold">{insights.length}</p>
          </div>
        </div>
        <div className="w-px h-8 bg-border" />
        <div className="flex items-center gap-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-muted">
            <CheckCircle className="h-4 w-4 text-[hsl(var(--success))]" />
          </div>
          <div>
            <p className="metric-label">Recommendations</p>
            <p className="text-xl font-semibold">{recommendations.length}</p>
          </div>
        </div>
        <div className="w-px h-8 bg-border" />
        <div className="flex items-center gap-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-muted">
            <AlertTriangle className="h-4 w-4 text-[hsl(var(--warning))]" />
          </div>
          <div>
            <p className="metric-label">Action Items</p>
            <p className="text-xl font-semibold">
              {recommendations.filter(r => r.toLowerCase().includes('consider') || r.toLowerCase().includes('review')).length}
            </p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card className="border-border h-full">
          <CardHeader className="pb-3 border-b bg-muted/30">
            <CardTitle className="flex items-center gap-2 text-base font-semibold text-foreground">
              <TrendingUp className="w-4 h-4 text-foreground" />
              Smart Insights
            </CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            {insights.length > 0 ? (
              <div className="divide-y divide-border">
                {insights.slice(0, 5).map((insight, index) => {
                  const insightType = getInsightType(insight)
                  return (
                    <div key={index} className="p-4 hover:bg-muted/30 transition-colors">
                      <div className="flex items-start gap-3">
                        <div className="mt-0.5 flex-shrink-0">
                          {getInsightIcon(insight)}
                        </div>
                        <div className="flex-1 space-y-1">
                          <p className="text-sm text-foreground leading-relaxed">{insight}</p>
                          <Badge variant="outline" className={cn("text-[10px] px-1.5 py-0 h-5 font-normal capitalize", insightType.className)}>
                            {insightType.type}
                          </Badge>
                        </div>
                      </div>
                    </div>
                  )
                })}
                {insights.length > 5 && (
                  <div className="p-3 text-center bg-muted/10">
                    <span className="text-xs text-muted-foreground">
                      +{insights.length - 5} more insights available
                    </span>
                  </div>
                )}
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-12 text-muted-foreground">
                <TrendingUp className="w-10 h-10 mb-3 opacity-20" />
                <p className="text-sm font-medium">No insights available yet</p>
              </div>
            )}
          </CardContent>
        </Card>

        <Card className="border-border h-full">
          <CardHeader className="pb-3 border-b bg-muted/30">
            <CardTitle className="flex items-center gap-2 text-base font-semibold text-foreground">
              <CheckCircle className="w-4 h-4 text-[hsl(var(--success))]" />
              Recommendations
            </CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            {recommendations.length > 0 ? (
              <div className="divide-y divide-border">
                {recommendations.slice(0, 6).map((recommendation, index) => (
                  <div key={index} className="p-4 hover:bg-muted/30 transition-colors">
                    <div className="flex items-start gap-3">
                      <CheckCircle className="w-4 h-4 text-[hsl(var(--success))] mt-0.5 flex-shrink-0" />
                      <p className="text-sm text-foreground leading-relaxed">
                        {recommendation}
                      </p>
                    </div>
                  </div>
                ))}
                {recommendations.length > 6 && (
                  <div className="p-3 text-center bg-muted/10">
                    <span className="text-xs text-muted-foreground">
                      +{recommendations.length - 6} more recommendations
                    </span>
                  </div>
                )}
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-12 text-muted-foreground">
                <CheckCircle className="w-10 h-10 mb-3 opacity-20" />
                <p className="text-sm font-medium">No recommendations available yet</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      <Card className="border-border bg-muted/10">
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2 text-base font-semibold text-foreground">
            <Shield className="w-4 h-4 text-foreground" />
            Suggested Actions
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {[
              "Review coverage gaps identified in your policies",
              "Compare premiums to find potential savings",
              "Set reminders for upcoming policy renewals",
              "Ask our AI assistant specific questions about your coverage"
            ].map((action, i) => (
              <div key={i} className="flex items-center gap-3 p-3 bg-background rounded-md border border-border hover:border-foreground/30 transition-colors cursor-pointer group">
                <div className="h-6 w-6 rounded-full bg-muted flex items-center justify-center flex-shrink-0 group-hover:bg-muted/80 transition-colors">
                  <ArrowRight className="w-3 h-3 text-muted-foreground" />
                </div>
                <span className="text-sm text-foreground font-medium">{action}</span>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
